name: Docker Image Build to Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build-to-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4
      
    - name: Build the Docker image to test
      run: docker build . --file Dockerfile --tag bentley-app:$(date +%s) --target builder
